### ISSUE TITLE
Add method renderFormatted(Appendable)

### ISSUE THREAD

**Issue by obecker** [tipsy/j2html#177]
Please add a method `renderFormatted(Appendable)` so that I can write a formatted version of the markup without intermediate `StringBuilder` to a file or similar.

**Comment by sembler** [comment]
I think this is a valuable feature to include.  But, perhaps this is also the time to consider addressing #159.  The tags classes are great for assembling the HTML tree, but I think we should try to extract the responsibilities of formatting (and any associated configuration of that formatting) into a separate class. I think it can be done in a backwards-compatible way.  Perhaps we start by adding methods like:

```
Renderable.render(-FORMAT_INTERFACE- format);
Renderable.render(-FORMAT_INTERFACE- format, Appendable appendable);
```

With -FORMAT_INTERFACE- offering methods for appending individual pieces of HTML syntax like:

```
appendTagStart()
appendTagName(String name)
appendAttribute(String name)
appendAttribute(String name, String value)
```
... and so on.

Tags would simply call those methods instead of appending directly to the StringBuilder.  This offers two things.  First, implementations of -FORMAT_INTERFACE- can encapsulate all of the relevant configuration details at the moment it is created.  That eliminates concerns about the static global Config fields in multithreaded environments, and still allows Config to continue to be used without breaking existing use cases.  Second, this provides a means of altering the output by providing different implementations of -FORMAT_INTERFACE-.  The j2html library can provide two implementations for what we currently offer, flat and tree formatting:

```
body(p("text")).render(Format.flat());
body(p("text")).render(Format.flat(), fileWriter);

body(p("text")).render(Format.tree());
body(p("text")).render(Format.tree(), fileWriter);

// Compatibility?
body(p("text")).render(); == body(p("text")).render(Format.flat());
```


But users could provide their own implementation that was customized to their needs (examples:  changing upper/lower case on tag names, reducing indentation for deeply nested elements, changing spacing between attributes, and more...)

That's my half-baked idea so far.  I do not wish to derail your request, but I think it would be best to address the larger difficulties of formatting and configuration before we add more single-purpose methods that would need to be maintained or deprecated later.

What are your ideas about this?

**Comment by obecker** [comment]
I see, yes that makes perfect sense. At first I thought we can do this refactoring based on my first simplification steps in https://github.com/tipsy/j2html/pull/178, but of course you are right that this would temporarily introduce a new method in the `Renderable` interface.

Are you going to tackle this new design in the near future? I leave it to you to decide whether my changes are helpful or not. I don't mind if the PR gets rejected if there is another solution that solves my needs. :-)

Cheers.
Oliver

**Comment by sembler** [comment]
My hope is to have a working branch this week.  Your solution looked fine.  It is just down to which direction we need to go, and I'm still feeling that out.  Thanks for your patience.

**Comment by sembler** [comment]
@tipsy I'm curious about your past plans for renderModel().  Most times the model argument is null.  Was it intended as a component feature? Are you aware of any uses of it outside of testing?

**Comment by tipsy** [comment]
@sembler I didn't add it, but it seems it was a performance improvement: https://github.com/tipsy/j2html/issues/83

**Comment by sembler** [comment]
Thanks!  I had not seen that pull request.  This is a way of using j2html that I've never needed, so I wasn't sure how it fit together until now.

**Comment by sembler** [comment]
It took longer than I desired, but I put together a PR ( #179 ) that may work for us.  But I'd like as many eyes on it as possible too, as I may not have hit all of the possible implications of inheritance.  The essence is that now all appending is done by an HtmlBuilder, which provides methods for defining tags, attributes, text, etc.  

The original methods for rendering still work, and use the FlatHtml or IndentedHtml builders in the background.  But if you need extra customization you can use the new rendering methods like: 

`
div().render(IndentedHtml.into(fileWriter, Config.defaults().withEmptyTagsClosed(true))).flush();
`

In this example we're rendering directly into an FileWriter, with tags and text indented and empty tags closed, then flushing it after rendering completes.  Config now allows you to create immutable instances, to eliminate the need to use global static fields (but that is still supported). Creating different Configs is as simple as calling one of the 'with*' methods on the class.
