### ISSUE TITLE
HTMLX Support

### ISSUE THREAD

**Issue by TareqK** [tipsy/j2html#215]
https://htmx.org/ is a library that adds extra tags to HTML to create new behaviors and follows the Localization of Behavior pattern. It would be great if we can support these extended tags in J2html, which would allow using j2html to build entire component-based webapps. 

Im more than happy to contribute the change, if its fine with the maintainers. Otherwise, is there a way to extends j2html to add more attributes on a tag? something like "xdiv", "ximg", etc, which would have the extra attributes?

**Comment by sembler** [comment]
I think it would need to be distributed as a separate Jar, and I'd expect there to be many changes under the hood as we progress towards version 2.0.

**Comment by TareqK** [comment]
I Dont mind doing it like that, by extending each base class. But should this be in this repo or another repo?

**Comment by sembler** [comment]
My initial impression from the htmx docs is that this is heavily focused on getting the correct content for the correct attributes.  To that end I'd suggest starting by defining small utilities to do that instead of worrying about deep integration with existing classes.  Like `Attribute put = HX.put("/messages")` so that you can the use the attribute in J2html `div().attr(HX.put("/messages"))` to get `<div hx-put="/messages"></div>`.  As you expand on that support class you could add features towards the specific syntax that HTMX recognizes like `hx-trigger="mouseenter once"`.  If you end up still pursuing integration with J2html you'll have all of those utilities ready to use behind the scenes.

**Comment by TareqK** [comment]
I went ahead and did that https://github.com/TareqK/j2htmx

**Comment by TareqK** [comment]
Closing this, as i created j2htmx to extend for now

**Comment by sembler** [comment]
Thanks @TareqK !  This looks really nice.  I like where you are going with your examples.
