### ISSUE TITLE
MathML support

### ISSUE THREAD

**Issue by matthew-mccall** [tipsy/j2html#219]
Is MathML support planned? Adding MathML would allow users to generate and share equations in their HTML using this library. If not, I'm willing to work on it and open a PR for it.

**Comment by tipsy** [comment]
> Is MathML support planned?

Not planned, but sounds pretty cool, IMO.

**Comment by sembler** [comment]
I'd also like to add support for MathML.  Since we've already had users ask for extensions to traditional html (like HTMX), it may be worth restructuring the J2html project to be a more formal Maven multi-module project which can build multiple artifacts.  Eventually we can incorporate those other projects and distribute their artifacts as add-ons.  It'll take a little effort to restructure but I'm happy to do it while @matthew-mccall  works towards MathML support.

**Comment by sembler** [comment]
Basic support for MathML has been added by #223 .  Further enhancements can be requested as new issues.
