### ISSUE TITLE
img tag

### ISSUE THREAD

**Issue by kumarvgit** [tipsy/j2html#52]
I am using j2Html and its great FOSS :)

Currently image TagCreater generates a short hand notation of closing tags i.e. <img .... />.

This is gives following error
The element type "img" must be terminated by the matching end-tag "</img>"

**Comment by tipsy** [comment]
Hi @kumarvgit. j2html is meant for HTML5, so empty/void tags are not closed. I would like to keep it this way, but could you explain why you can't use HTML5?

**Comment by chmuche** [comment]
I have the case because I use J2Html to create webComponent.
And I need a <tag></tag> event if the content is empty
I think create a custom printer, with some option, like Generate end tag, and a pretty print option too.
The custom printer can be passed to the #render() method.
By default if no printer is given then the DefaultPrinter is applied.

**Comment by tipsy** [comment]
> I think create a custom printer, with some option, like Generate end tag, and a pretty print option too.
> The custom printer can be passed to the #render() method.
> By default if no printer is given then the DefaultPrinter is applied.

Sounds like a good idea.

**Comment by kumarvgit** [comment]
Hi @tipsy, Thank you for your reply.
I need to further process HTML generated and convert it to PDF, the PDF engine does not accept short hand notations.

Currently i am using a workaround by creating an empty tag and filling string in it.
