### ISSUE TITLE
Question about bootstrap (and other js libs)

### ISSUE THREAD

**Issue by valtterip** [tipsy/j2html#77]
Hi, I hope raising a new issue is okay for this eve though it's actually a question. There is a following statement on the j2html homepage: "Please don't use j2html if: You use a CSS framework such as Bootstrap." I would assume this is quite a show stopper for many.

However, if I understand properly what j2html does, this only affects cases where pretty much the whole html is rendered by the j2html, including the head / body etc, but does it really matter when generating just parts of the html with j2html?

For example if my java server returns a snippet that is meant to be injected into a div by whatever means, does it really matter which libs are used in the frontend? For me j2html would be really useful server side html component creator, but I might have understood something completely wrong..

Thanks!

**Comment by tipsy** [comment]
> I understand properly what j2html does, this only affects cases where pretty much the whole html is rendered by the j2html, including the head / body etc, but does it really matter when generating just parts of the html with j2html?

Yes, that's correct.

> For example if my java server returns a snippet that is meant to be injected into a div by whatever means, does it really matter which libs are used in the frontend? For me j2html would be really useful server side html component creator, but I might have understood something completely wrong..

Sounds like a reasonable use-case, I don't think you've misunderstood anything.

It doesn't matter what libs are used on the frontend, and you **could** use j2html to build bootstrap markup. But you would probably end up hating j2html, since bootstrap has very verbose markup that they want you to copy from the docs. For example, converting a bootstrap modal to j2html would be very cumbersome. I can specify this on the index page.

**Comment by valtterip** [comment]
All right then, thank you!
